[package]
name = "shadow-spatial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = { workspace = true }
shadow-ecs = { path = "../shadow-ecs", version = "0.1.0" }
