[package]
name = "shadow-ecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ulid = { workspace = true }
crc32fast = { workspace = true }
ahash = "0.8.11"
